spring.application.name=hotelbooking-v2
spring.jackson.serialization.indent-output=true

spring.datasource.url=jdbc:postgresql://localhost:5432/bd_hostels
spring.datasource.username=postgres
spring.datasource.password=10345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false


